backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "proyek"
    label: "Proyek Terbaru"
    folder: "data/proyek"
    create: true
    format: "yaml"
    extension: "yaml"
    slug: "{{slug}}"
    summary: "{{title}}" # ⬅️ tampilkan judul di list
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Deskripsi", name: "description", widget: "text" }


