backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "proyek"
    label: "Proyek Terbaru"
    label_singular: "Proyek"
    folder: "data/proyek"       
    create: true
    delete: true
    format: "yaml"
    slug: "{{slug}}"            
    fields:
      - label: "Judul"
        name: "title"
        widget: "string"
      - label: "Deskripsi"
        name: "description"
        widget: "text"
      - label: "Gambar"
        name: "image"
        widget: "image"
